platform: [ ethereum, binance ]

# can be tokens or notifications
subscriber: notifications
# can be swagger, tokens or notifications
rest_api: all

observer:
    backlog: 3h
    backlog_max_blocks: 100
    txs_batch_limit: 5000
    fetch_blocks_interval: 100ms
    push_notifications_batch_limit: 50
    block_poll:
        min: 1s
        max: 30s
    rabbitmq:
        uri: amqp://guest:guest@localhost:5672
        consumer:
            prefetch_count: 10

postgres:
    uri: postgresql://user:pass@localhost:5432/my_db?sslmode=disable
    read_uri: postgresql://user:pass@localhost:5432/my_db?sslmode=disable
    log: true

binance:
    api: https://dex.binance.org/api
    explorer: https://explorer.binance.org/api

ethereum:
    api: https://localhost:4567 #(Trust-Ray API)
    blockbook_api: https://eth1.trezor.io/api
    collections_api: https://api.opensea.io
    rpc: https://main-rpc.linkpool.io
