version: '3.7'
services:
  platform_api:
    container_name: api
    build:
      context: .
      args:
        - SERVICE=api
    depends_on:
      - rabbit
      - postgres
    ports:
      - 8420:8420
      - 8437:8437
    network_mode: host

  observer_notifier:
    build:
      context: .
      args:
        - SERVICE=notifier
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    network_mode: host

  observer_parser:
    build:
      context: .
      args:
        - SERVICE=parser
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    network_mode: host

  observer_subscriber:
    container_name: subscriber
    build:
      context: .
      args:
        - SERVICE=subscriber
    depends_on:
      - rabbit
      - postgres
    restart: on-failure
    network_mode: host

  rabbit:
    container_name: rabbit
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - "5672"
      - "15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=my_db
    ports:
      - 5432:5432
    expose:
      - "5432"
